### ISSUE TITLE
[Frontend] [Issue] Search HOA Member Properties

### ISSUE THREAD

**Issue by camayacoast** [camaya-softdev/hoa-portal-front#11]
**Context of the Problem:**
 No data showing when searching HOA Member Properties by Street Name, Lot, Lot Area (SQM)

**Proposed Solution:**
 Must show accurate data when searching HOA Member Properties by Street Name, Lot, Lot Area (SQM)

**Screenshots:**
 
**Related Files:**
https://contextus.sharepoint.com/:x:/s/ITSoftwareDevelopment/EeFnyM3Zr5hIn5k-U1kkWN4BY-yELBIjO4LQGHuAZ4oNsg?e=8ACEFI

**Comment by rouelcalzita** [comment]
Search by HOA Member Properties by Street Name, Lot, Lot Area (SQM) **- Passed**
