### ISSUE TITLE
[Frontend] [Issue] HOA Member Documents

### ISSUE THREAD

**Issue by camayacoast** [camaya-softdev/hoa-portal-front#12]
**Context of the Problem:**
1. Documents table disappears after uploading documents
2. And also document table disappears after searching by 
a. Document Name
b. Document Description
c. Document Tag

**Proposed Solution:**
 Document table must show after uploading documents

**Screenshots:**
 
**Related Files:**
https://contextus.sharepoint.com/:x:/s/ITSoftwareDevelopment/EeFnyM3Zr5hIn5k-U1kkWN4BY-yELBIjO4LQGHuAZ4oNsg?e=8ACEFI

**Comment by rouelcalzita** [comment]
1. Documents table disappears after uploading documents **- Passed**
2. Search by **- Failed**
a. Document Name
b. Document Description
c. Document Tag

**Comment by cctc-rouelcalzita** [comment]
### QA Approved!
**Test Environment: Production**

Search by : **- Passed**
a. Document Name
b. Document Description
c. Document Tag
