### ISSUE TITLE
[Frontend] [Issue] Searching RFID

### ISSUE THREAD

**Issue by camayacoast** [camaya-softdev/hoa-portal-front#13]
**Context of the Problem:**
 No data is showing when searching in RFID page

**Proposed Solution:**
Accurate data must show when searching in RFID page
 
**Screenshots:**
 
**Related Files:**
https://contextus.sharepoint.com/:x:/s/ITSoftwareDevelopment/EeFnyM3Zr5hIn5k-U1kkWN4BY-yELBIjO4LQGHuAZ4oNsg?e=8ACEFI

**Comment by MManuelCamaya** [comment]
For search:

RFID ID 
Semnox No
Status
Member Id
Member Name

**Comment by rouelcalzita** [comment]
**Test Environment: Prod**

search box input Member ID, Member name **- Passed**
