### ISSUE TITLE
[Frontend][Issue] Privilege Transaction Table

### ISSUE THREAD

**Issue by camayacoast** [camaya-softdev/hoa-portal-front#14]
**Context of the Problem:**
 The privilege transaction table disappears if user avails a privilege

**Proposed Solution:**
 The privilege transaction table must not disappear even after the user avails a privilege

**Screenshots:**
 
**Related Files:**
https://contextus.sharepoint.com/:x:/s/ITSoftwareDevelopment/EeFnyM3Zr5hIn5k-U1kkWN4BY-yELBIjO4LQGHuAZ4oNsg?e=8ACEFI

**Comment by rouelcalzita** [comment]
Error 404 upon deleting


![Image](https://github.com/camaya-softdev/hoa-portal-front/assets/150649513/69f3e183-e30b-4521-b0c8-10520e034c65)

**Comment by camayacoast** [comment]
I. Error 404 upon deleting - this is currently not working, as it is still to be discussed if we should really put a delete button as these are transactions.

**Comment by camayacoast** [comment]
Will create a separate ticket for I. Error 404 upon deleting

**Comment by camayacoast** [comment]
Confirmed working

**Comment by cctc-rouelcalzita** [comment]
### QA Approved!
**Test Environment: Production**
Test privilege transaction table disappears if user avails a privilege **- Passed**
