### ISSUE TITLE
[Frontend] [Service] Post-deployment Regression Testing [08Feb2024]

### ISSUE THREAD

**Issue by camayacoast** [camaya-softdev/hoa-portal-front#16]
**Context of the Problem:**
Test all features, functionalities of modules, components, sub-components of HOA Portal Phase 1 to ensure compliance and functionality.

**Proposed Solution:**
Perform a thorough regression testing of HOA Portal.

**Screenshots:**

**Related Files:**

**Comment by cctc-rouelcalzita** [comment]
### QA Disapproved!

**Test Environment: Production**
