### ISSUE TITLE
[Frontend] [Issue] Search Subdivision

### ISSUE THREAD

**Issue by camayacoast** [camaya-softdev/hoa-portal-front#7]
**Context of the Problem:**
Login > Admin Management > Subdivision Management

No data when Searching By Subdivision ID, Area (SQM), Total block, Lot,  Cutoff date, Payment Targets, Contact Person, & Contact #

**Proposed Solution:**
Add searching by Subdivision ID, Area (SQM), Total block, Lot,  Cutoff date, Payment Targets, Contact Person, & Contact #

**Screenshots:**

**Related Files:**
https://hoaportal.camayacoast.com/login

https://contextus.sharepoint.com/:x:/s/ITSoftwareDevelopment/EeFnyM3Zr5hIn5k-U1kkWN4BY-yELBIjO4LQGHuAZ4oNsg?e=8ACEFI

**Comment by rouelcalzita** [comment]
No data on search:

- [ ] By Subdivision ID **- Passed**
- [ ] Area (SQM) **- Failed**
- [ ] Total block **- Failed**
- [ ] Cutoff date **- Passed**
- [ ] Payment Targets **- Passed**
- [ ] Contact Person **- Failed**
- [ ] Contact # **- Passed**

**Comment by camayacoast** [comment]
Area (SQM) search was not included as it is not required, most Subdivision inputs does not have Area(SQM)

**Comment by MManuelCamaya** [comment]
Hi good day upon checking po yung sa contact person is working as intended mey mga problem lang sa mismong data I've check the database and mey mga double space pangalan pero would help if it was a different issue 

tapos yung sa total block naman masyado na kasi marami yung search parameters soo when you search something either hindi lalabas or lalabas pero it is present sa other column leading sa inaccurate data

**Comment by cctc-rouelcalzita** [comment]
### QA Approved!
**Test Environment: Production**

No data on search:
- [ ] By Subdivision ID **- Passed**
- [ ] Cutoff date **- Passed**
- [ ] Payment Targets **- Passed**
- [ ] Contact Person **- Passed**
- [ ] Contact # **- Passed**
