### ISSUE TITLE
[Frontend] [Issue] Board of Directors

### ISSUE THREAD

**Issue by camayacoast** [camaya-softdev/hoa-portal-front#8]
**Context of the Problem:**
 Login > Admin Management > Subdivision Management > Board of Directors
- Board of Directors table disappears after adding a board of director and will re-appear once refreshed
- Board of director description column wrong in spelling

**Proposed Solution:**
1. Board of Directors table must not disappear after adding a board of director
2. Correct the spelling of Description

**Screenshots:**
<img width="145" alt="image" src="https://github.com/camaya-softdev/hoa-portal-front/assets/98928952/a6566790-71c2-478f-b116-9ef55cf1367b">

 
**Related Files:**
https://hoaportal.camayacoast.com/subdivision

https://contextus.sharepoint.com/:x:/s/ITSoftwareDevelopment/EeFnyM3Zr5hIn5k-U1kkWN4BY-yELBIjO4LQGHuAZ4oNsg?e=8ACEFI

**Comment by rouelcalzita** [comment]
Board of Directors table disappears after adding a board of director and will re-appear once refreshed **- Failed** (After adding same *FULL NAME* the board of directors will disappear)

![Image](https://github.com/camaya-softdev/hoa-portal-front/assets/150649513/f6d84df3-c8b9-4ccb-b303-e380860cdb26)


Board of director description column wrong in spelling **- Passed**

**Comment by MManuelCamaya** [comment]
I was able to add board of directors, and when a director is existing it updates it automatically
,maybe can ask your assistant to live check with you sir @cctc-rouelcalzita 


![Image](https://github.com/camaya-softdev/hoa-portal-front/assets/144507982/29e5c6ad-68df-49ef-8f15-b4bac056fd7c)

**Comment by cctc-rouelcalzita** [comment]
### QA Approved!
**Test Environment: Production**
1. Board of Directors table disappears after adding a board of director and will re-appear once refreshed **- Passed** (After adding same *FULL NAME* the board of directors will disappear)

2. Board of director description column wrong in spelling **- Passed**
