### ISSUE TITLE
[Front/Backend] [Issue] Edit Board of Director

### ISSUE THREAD

**Issue by camayacoast** [camaya-softdev/hoa-portal-front#9]
**Context of the Problem:**
 Showing error once Edit button is clicked

**Proposed Solution:**
 Check cause of error, and must show correct notification.

**Screenshots:**
 
**Related Files:**
https://contextus.sharepoint.com/:x:/s/ITSoftwareDevelopment/EeFnyM3Zr5hIn5k-U1kkWN4BY-yELBIjO4LQGHuAZ4oNsg?e=8ACEFI

**Comment by rouelcalzita** [comment]
Edit Board of Director#9 **- Passed**
